server.port: 8004

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/like
    username: root
    password: qwer1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
